# Site settings
title: Airy Fairy
email: arasyi@gmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arasyi.github.io" # the base hostname & protocol for your site
twitter_username: arifrasyidi
github_username:  arasyi

# Build settings
markdown: redcarpet
timezone: Asia/Jakarta
redcarpet:
  extensions: [
    footnotes,
    smart,
    tables,
    fenced_code_block,
    no_intra_emphasis,
    autolink,
    strikethrough,
    with_toc_data,
    lax_spacing,
    highlight
  ]
kramdown:
  input: GFM

permalink: /:year/:month/:day/:title.html

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comment: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

gems:
 - jekyll-sitemap

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - new.cmd
  - jekyll.thor
  - archive.php
  - jek.cmd
  - new-old.cmd
  - new.php
