# Site settings
title: Airy Fairy
email: arasyi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am awesome! ^^
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arasyi.github.io" # the base hostname & protocol for your site
twitter_username: arifrasyidi
github_username:  arasyi

# Build settings
markdown: redcarpet
timezone: Asia/Jakarta
redcarpet:
  extensions: [
    footnotes,
    smart,
    tables,
    fenced_code_block,
    no_intra_emphasis,
    autolink,
    strikethrough,
    superscript,
    with_toc_data,
    lax_spacing,
    highlight
  ]
kramdown:
  input: GFM

highlighter: null

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comment: true
      permalink: /:year/:month/:day/:title.html
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "projects"
      type: "posts"
    values:
      permalink: /projects/:title.html

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - new.cmd
  - jekyll.thor
  - archive.php
